### ISSUE TITLE
Keyword Arguments / Regularizer Interface

### ISSUE THREAD

**Issue by JakobAsslaender** [JuliaImageRecon/RegularizedLeastSquares.jl#30]
Hi,

I wonder if it would make sense to move away from using keyword arguments for the regularizer and `prox!` functions. Foremost, I fear that there are cases in which the function itself does not have sufficient information for a meaningful default. E.g., the function `proxLLR!` requires the parameter `shape` and right now, the default is implemented as `shape::Ntuple=[]`, which will throw an error (in the PR #29 I changed this the default to `error()` to avoid confusions). Additionally, keyword in function calls are rather slow and should be avoided in inner functions. This is arguably more of an academic concern, I guess in most use cases this is negligible. 

To make the requirements of each regularization more transparent, we could utilize the already implemented `abstract type AbstractRegularization`, and move away from packing all different regularizers in the type `Regularization`, but instead have their own concrete type that replace `params::Dict{Symbol,Any}` with explicit versions of the parameters. The comment `# @TODO in die funcs` in the code indicates to me, that you might have thought about something similar yourself before ;). 

Any thoughts?

**Comment by tknopp** [comment]
A partial answer:

> Additionally, keyword in function calls are rather slow and should be avoided in inner functions. This is arguably more of an academic concern, I guess in most use cases this is negligible.

I doubt that this is true. They were slower in old Julia versions but nowadays they should have identical performance. I quickly found this discourse topic where it was discussed: https://discourse.julialang.org/t/performance-of-typed-keyword-arguments/11579/8?u=tknopp
This is, by the way, why Julia moved most things to keyword parameters in Julia 1.0. The `dims` keyword argument is the best example.

**Comment by JakobAsslaender** [comment]
Got it. My own benchmark might have been spurious. Yet, this was not my main motivation...

**Comment by migrosser** [comment]
I kind of like the idea. In fact I think that @hofmannmartin once suggested a similar thing. Having a type hierarchy would also allows us to dispatch on it and check whether a solver can deal with a given regularizer. For instance, our current CGNR implementation only supports l2-regularization. 

An issue which might be somewhat related is that it would be nice to make our interface compatible with [ProximalOperators.jl](https://github.com/JuliaFirstOrder/ProximalOperators.jl). In terms of regularization this might give us quite a bit of functionality for free.

**Comment by JakobAsslaender** [comment]
Great, let's look into that once one of us finds the time. One thing I would like about that approach is that it would create a constructor or function for each regularization instead of one that takes a string for an argument. IMHO, the latter makes it difficult to use the tools for an IDE for getting information on the functions arguments and one kinda has to know that algorithm A needs a `shape` argument etc., or it at least requires multiple steps through all the wrapper functions.

**Comment by JeffFessler** [comment]
BTW, ProximalOperators has the correct version of the prox for l1 here using `sign`:
https://github.com/JuliaFirstOrder/ProximalOperators.jl/blob/5b2845a2d34f61a4e002ee28801ae1de5da8639f/src/functions/normL1.jl#L127

whereas currently RLS has an eps that adds unnecessary computation:
https://github.com/tknopp/RegularizedLeastSquares.jl/blob/22d58db104e374232a4e7d99b8863cd5a3ac36af/src/proximalMaps/ProxL1.jl#L18

Using PO could have the benefit of more eyes on such details.

**Comment by JakobAsslaender** [comment]
Interesting! I am not sure that I was aware of the [ProximalOperators.jl](https://github.com/JuliaFirstOrder/ProximalOperators.jl) and [ProximalAlgorithms.jl](https://github.com/JuliaFirstOrder/ProximalAlgorithms.jl) packages--and it looks like the intention behind these packages is very similar to RLS.jl, isn't it? Any reason why we are not joining forces with them, @tknopp ?

**Comment by JakobAsslaender** [comment]
Haha, sorry. No offense at all intended!!! This was just me trying to use the current momentum to move things forward. How about his agenda: We draft in a branch an adoption to the syntax used in PO.jl, but keep the code here for now. If this works for us, we can merge the branch into our master and then start a discussion with the maintainer of PO.jl if we should move code over. Does that make sense? But we need to mature some of the functions a bit more, I think. E.g., my postdoc @sflassbeck has started to work on generalizing the TV prox operator to ND.
