### ISSUE TITLE
Broken getting started

### ISSUE THREAD

**Issue by AaronGhost** [JuliaImageRecon/RegularizedLeastSquares.jl#53]
Hi, thank you for developing this library!

I have been trying to follow the Getting Started tutorial but I get an error when attempting to build the `SamplingOp`:
```julia
using RegularizedLeastSquare
A = SamplingOp(idx, (N, N))
```
But I obtain the error: `ERROR: UndefVarError: SamplingOp not defined.`
I have tried to continue by building A either as a matrix or a vector and similarly for y. But I obtain mismatch errors when calling the solve function.

Thanks for your help!

**Comment by nHackel** [comment]
Hello,

sorry for the late reply. I'm just taking a look at our issue backlog. With the latest releases of RegularizedLeastSquares.jl we have also updated the documentation and this issue should be fixed now
