### ISSUE TITLE
Package conflict with function `factor` 

### ISSUE THREAD

**Issue by JakobAsslaender** [JuliaImageRecon/RegularizedLeastSquares.jl#61]
Hi! 
Would it be possible to rename (or not export) the function `factor`? It conflicts with `Primes.jl` where the function calculates the factors of an integer. 
```
julia> using Primes
julia> using RegularizedLeastSquares
julia> factor
WARNING: both Primes and RegularizedLeastSquares export "factor"; uses of it in module Main must be qualified
ERROR: UndefVarError: `factor` not defined
```

I personally would also find it helpful to have a more descriptive function name. 

Many thanks!
-ja

**Comment by nHackel** [comment]
This was closed with version 0.11.2
