### ISSUE TITLE
[Bug] ADMM verbose doesn't work anymore

### ISSUE THREAD

**Issue by SebastianFlassbeck** [JuliaImageRecon/RegularizedLeastSquares.jl#93]
If ADMM is run with `verbose = true`, it throws an error in line 207 in ADMM.jl since the variable `iteration` doesn't exist.
I'm guessing that `state.iteration` instead, should fix it but I didn't look through the code thoroughly.

**Comment by nHackel** [comment]
Yes that should fix it. I can push that change to master but the earliest time I can do that is in 2+ days

**Comment by nHackel** [comment]
Maybe a more fundamental question is if we can replace verbose with some callback that has verbose printing for each solver or if we can replace verbose with Julias logging system.

I havent used the keyword yet, so Im not sure whats the most convenient from a user perspective. Do you have a preference? 

Or maybe @JakobAsslaender you have one?

I could maybe sketch up verbosecallback in the next week

**Comment by JakobAsslaender** [comment]
Hmm, my first instinct is that a callback is a rather complicated way of printing some convergence measures. Beyond this first instinct, I would try and keep it similar to other packages, but I would need look into the common practices.

**Comment by SebastianFlassbeck** [comment]
Thanks. I don't have any preferences. FYI, the outputs in lines 267-271 also need a `state.`.

**Comment by nHackel** [comment]
Should be fixed with the latest (currently being released) version. I've also added tests for the verbose keyword
